client:
  image: node:18
  script:
    - npm install -g elm elm-spa
    - cd Client
    - elm-spa make --optimize
  artifacts:
    paths:
      - Client/public

server:
  image: swift:5.6-bionic
  script:
    - apt-get update -qy
    - apt-get install -y libsqlite3-dev upx
    - swift build -c release -Xswiftc -static-executable
    - mv .build/release/Run Polinpin
  artifacts:
    paths:
      - Polinpin